---
- name: set OS dependent variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml'
    - '{{ ansible_facts.distribution }}.yml'
    - '{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml'
    - '{{ ansible_facts.os_family }}.yml'
  tags: always

- include: configure.yml
  when: mysql_hardening_enabled | bool
  tags:
    - mysql_hardening

- include: mysql_secure_installation.yml
  when: mysql_hardening_enabled | bool
  tags:
    - mysql_hardening
    - mysql_secure_installation
