apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: linodebs.csi.linode.com
  creationTimestamp: "2020-10-24T18:53:48Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/linodebs-csi-linode-com
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:pv.kubernetes.io/provisioned-by: {}
      f:spec:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:claimRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
          f:resourceVersion: {}
          f:uid: {}
        f:csi:
          .: {}
          f:driver: {}
          f:fsType: {}
          f:volumeAttributes:
            .: {}
            f:storage.kubernetes.io/csiProvisionerIdentity: {}
          f:volumeHandle: {}
        f:persistentVolumeReclaimPolicy: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: csi-provisioner
    operation: Update
    time: "2020-10-24T18:53:48Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          v:"external-attacher/linodebs-csi-linode-com": {}
    manager: csi-attacher
    operation: Update
    time: "2020-10-24T18:53:52Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-10-25T07:54:12Z"
  name: pvc-63e3aa9d56f044b4
  resourceVersion: "214892"
  selfLink: /api/v1/persistentvolumes/pvc-63e3aa9d56f044b4
  uid: b2a229aa-d0cc-41aa-b69d-981f28dc4cf9
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pgadmin
    namespace: default
    resourceVersion: "191275"
    uid: 63e3aa9d-56f0-44b4-b8ba-22752ef4b33d
  csi:
    driver: linodebs.csi.linode.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1603189533155-694-linodebs.csi.linode.com
    volumeHandle: 94776-pvc63e3aa9d56f044b4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: linode-block-storage-retain
  volumeMode: Filesystem
status:
  phase: Released
