apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01UQXlNREV3TWpFd01Wb1hEVE13TVRBeE9ERXdNakV3TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjFsCmdMaHd5Y0YyTXFUOGFiOGM2aDV6dFovREVnSjJaN2NMSWFDMTBFd0JSVkJwM0EwWVcvc2RpeFpDZVgxWlY2UnUKaCsxYnpOaW5BUzl3M2VaR042R1JDY014YllKWXhxVDZmYkxWeHRWZEVNaXZueWRQYkF5b1pTQzAxZEgrcWVGRApEd0FpbGdPemgwOVNmK3NsZHdqYWxrMzdaZGo4UGNUanNGZHZ6TjNCMk52b1d5QktqSlMvZzcrWU83dSttUnRxCmRVMUh1TkIvYU9FQWVjZ2VudUVVT1FUNkIxeWZ4Y0pCZ0NTZi9vVWgwNHloOEVFNnJXOTQvb0Y1S1laajRsdTcKSElsdVVOcnpEQllJMC9MZlYwdmExNDN5SW41YnhoS1VhV085cXh6Rjd1NStYbStNL2FyT2FWcStoNnRWS3QwYgorQU9BQzByT1B3SGVUSGdEV2xNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNUjQ1ZS9Cay8vMjRwY1pWRVNvYm9pdm1CRlYKMXVtc3laeUFpQ0Y2YUNBU1RkcWZjb0lUY00rdndFNW8zaWZYOU9Qc1NlaFN0akFSS3dhQTI1ZFRSODM4cUtFVwpHRFh2UHdxT0x0TkpaZTAwemJRMEtBOEE0ZmN3NTY3a2NoaElNOXBMSGJjaDJySlVzVlVlVStoMEZ2cFBvdGgvCnN1cVJZbkhnQjVUSUF1OWI3c2ZjSmRCY28rQzR4T1g4ZHM5Q0VPSGRESjRFcWRBaTZ5T2kvQllyRW00Sy85OTEKL2o4TXV0elhnbjMyV1ZRc2Z2blRSYzdmMmk0bjZ0ZCt2ZlVNbklJbWU2UUdkaHE1SUYxQjVjdW5rd1h4UC9DaApiQlluRzVlN2VGeEMwSFl0OXdjd1dTUjBmYUQ1MkJ4MnI1OEwxSWtCRGc4bER6UmlqOWRWQnpjOUloZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://6016c09b-267e-47d9-a11f-c916ce01bb57.ap-west-1.linodelke.net:443
  name: lke11856

users:
- name: lke11856-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ikcyd3hmN3FBS2lUN3c0cjB2OGc0UkViTzJLZHBxVmduekdnZENuc1RVZjQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tN2I5NDIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZjM0YzAyOTgtY2EyYS00NjQxLWE5OGItNjEyZGZiNTAxNDVhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.keC36HspQzYkh4IRcvJaBACxWOpcXzJnplfUH1t83VocyvNe9jmMCPtAkJVP1IOqc7kE_fXsnZEXFMrKtyA7UxsZUaK21zIxy_aELpzwKBnbotdtYEogBZv-6z_Sp3UxMH0c7HzNmWtAZUXwyWHGM5oV-1FpACCmekKixSvgTog3h4mIUymxso_mwTGpnrLJtNwYC1jAShiOnj68yt4f3qwwbkgeCZRkFOFYSTrH-PQKaFesgVFOTc40O9o5-dhONKU1GqXB34UcpPGi6qqPlo249wbWxj8Cg7TMBaJ1GHlC_gJ-pQ9yWwHtC6W9HoCc7BrCx7xREZEhrgmMhF9YKA

contexts:
- context:
    cluster: lke11856
    namespace: default
    user: lke11856-admin
  name: lke11856-ctx

current-context: lke11856-ctx
